export const houseCommitteeSubcommittees: Record<string, string[]> = {
  Agriculture: [
    "Commodity Markets, Digital Assets, and Rural Development",
    "Conservation, Research, and Biotechnology",
    "Forestry and Horticulture",
    "General Farm Commodities, Risk Management, and Credit",
    "Livestock, Dairy, and Poultry",
    "Nutrition and Foreign Agriculture",
  ],
  Appropriations: [
    "Agriculture, Rural Development, Food and Drug Administration, and Related Agencies",
    "Commerce, Justice, Science, and Related Agencies",
    "Defense",
    "Energy and Water Development and Related Agencies",
    "Financial Services and General Government",
    "Homeland Security",
    "Interior, Environment, and Related Agencies",
    "Labor, Health and Human Services, Education, and Related Agencies",
    "Legislative Branch",
    "Military Construction, Veterans Affairs, and Related Agencies",
    "National Security, Department of State, and Related Programs",
    "Transportation, Housing and Urban Development, and Related Agencies",
  ],
  "Armed Services": [
    "Cyber, Information Technologies, and Innovation",
    "Intelligence and Special Operations",
    "Military Personnel",
    "Readiness",
    "Seapower and Projection Forces",
    "Strategic Forces",
    "Tactical Air and Land Forces",
  ],
  Budget: [],
  "Education and Workforce": [
    "Early Childhood, Elementary, and Secondary Education",
    "Health, Employment, Labor, and Pensions",
    "Higher Education and Workforce Development",
    "Workforce Protections",
  ],
  "Energy and Commerce": [
    "Commerce, Manufacturing, and Trade",
    "Communications and Technology",
    "Energy",
    "Environment",
    "Health",
    "Oversight and Investigations",
  ],
  Ethics: [],
  "Financial Services": [
    "Capital Markets",
    "Digital Assets, Financial Technology and Artificial Intelligence",
    "Financial Institutions",
    "Housing and Insurance",
    "National Security, Illicit Finance, and International Financial Institutions",
    "Oversight and Investigations",
  ],
  "Foreign Affairs": [
    "Africa",
    "East Asia and Pacific",
    "Europe",
    "Middle East and North Africa",
    "Oversight and Intelligence",
    "South and Central Asia",
    "Western Hemisphere",
  ],
  "Homeland Security": [
    "Border Security and Enforcement",
    "Counterterrorism and Intelligence",
    "Cybersecurity and Infrastructure Protection",
    "Emergency Management and Technology",
    "Oversight, Investigations, and Accountability",
    "Transportation and Maritime Security",
  ],
  "House Administration": [
    "Elections",
    "Modernization",
    "Oversight",
  ],
  Judiciary: [
    "Administrative State, Regulatory Reform, and Antitrust",
    "Constitution and Limited Government",
    "Courts, Intellectual Property, Artificial Intelligence, and the Internet",
    "Crime and Federal Government Surveillance",
    "Immigration Integrity, Security, and Enforcement",
    "Responsiveness and Accountability to Oversight",
  ],
  "Natural Resources": [
    "Energy and Mineral Resources",
    "Federal Lands",
    "Indian and Insular Affairs",
    "Oversight and Investigations",
    "Water, Wildlife and Fisheries",
  ],
  "Oversight and Government Reform": [
    "Cybersecurity, Information Technology, and Government Innovation",
    "Delivering on Government Efficiency",
    "Economic Growth, Energy Policy, and Regulatory Affairs",
    "Federal Law Enforcement",
    "Federal Law Enforcement and Oversight",
    "Government Operations",
    "Health Care and Financial Services",
    "Military and Foreign Affairs",
  ],
  Rules: [
    "Legislative and Budget Process",
    "Rules and Organization of the House",
  ],
  "Science, Space, and Technology": [
    "Energy",
    "Environment",
    "Investigations and Oversight",
    "Research and Technology",
    "Space and Aeronautics",
  ],
  "Small Business": [
    "Contracting and Infrastructure",
    "Economic Growth, Tax, and Capital Access",
    "Innovation, Entrepreneurship, and Workforce Development",
    "Oversight, Investigations, and Regulations",
    "Rural Development, Energy, and Supply Chains",
  ],
  "Transportation and Infrastructure": [
    "Aviation",
    "Coast Guard and Maritime Transportation",
    "Economic Development, Public Buildings, and Emergency Management",
    "Highways and Transit",
    "Railroads, Pipelines, and Hazardous Materials",
    "Water Resources and Environment",
  ],
  "Veterans' Affairs": [
    "Disability Assistance and Memorial Affairs",
    "Economic Opportunity",
    "Health",
    "Oversight and Investigations",
    "Technology Modernization",
  ],
  "Ways and Means": [
    "Health",
    "Oversight",
    "Social Security",
    "Tax",
    "Trade",
    "Work and Welfare",
  ],
};

export const houseCommittees = Object.keys(houseCommitteeSubcommittees);
